### ISSUE TITLE
add full analog stick support

### ISSUE THREAD

**Issue by sam0x17** [sam0x17/XJoy#1]
By default (with no calibration / messages sent back to the Joy-Con), the Joy-Con supports 8-direction movement of both analog sticks, which is sent via data slot 3. Looking at other Joy-Con libraries, it is difficult to determine whether this can be increased to something more analog with some calibration. If anyone has any idea whether it is possible to do this, and what the procedure is for getting the Joy-Con out of the default 8-direction mode for analog sticks, it would be greatly appreciated.

update: this is fully possible, and I am working on adding it to XJoy

**Comment by XepherX** [comment]
it looks like this will help you:

https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md#standard-input-report---stick-data

**Comment by sam0x17** [comment]
@XepherX thank you so much for this I will look through and see what I can find

**Comment by AceHack** [comment]
Thank you for this +10 looking forward to it.

**Comment by sjobeek** [comment]
Hey there!  Great project - just got it up and running with a few tweaks for my particular setup and it worked like a charm. 

I did however run into the 8-direction limitation in a game I'm playing - I'm also a developer and wouldn't mind helping out with the implementation if you have a feature branch in progress I could contribute to or need any help with debug / testing etc.

**Comment by sam0x17** [comment]
@sjobeek I would really appreciate the help as I have no time to work on this. The link @XepherX posted above should help you get started. Basically my understanding is there is some sort of initialization sequence that needs to be sent to the joycon to tell it to send full analog data. Otherwise that data just doesn't get broadcast in any way. By default if you dont do the initialization sequence it will stay in 8-directional mode and the LED will continue blinking as if it is trying to pair, so you may be able to kill two birds with one stone with this.

Feel free to simply clone the repo and do your changes there and then I will merge any working pull requests that get sent in.

Thanks again!!

-Sam

**Comment by sjobeek** [comment]
Sam, 

I ended up doing a bit more searching and came across another emulation project which has apparently has the analog input configured:

https://github.com/Davidobot/BetterJoyForCemu

This ended up solving my needs for now - thanks again though!

**Comment by HarryPeach** [comment]
> @sjobeek I would really appreciate the help as I have no time to work on this. The link @XepherX posted above should help you get started. Basically my understanding is there is some sort of initialization sequence that needs to be sent to the joycon to tell it to send full analog data. Otherwise that data just doesn't get broadcast in any way. By default if you dont do the initialization sequence it will stay in 8-directional mode and the LED will continue blinking as if it is trying to pair, so you may be able to kill two birds with one stone with this. I'd be happy to answer any questions you have about the code or to help brainstorm -- I just don't have time to work on the code myself.

Looking at that reverse engineering page, the JoyCon is in "Simple HID Mode", using subcommand 0x03 to set it to "Standard Full mode" would hopefully return the data we want.

I'll look into it a bit and see if I can make any progress

**Comment by sam0x17** [comment]
@HarryPeach thanks I appreciate it. Again I haven't had any time to work on this but I'll test and do a release if you guys can get it working

**Comment by HarryPeach** [comment]
I managed to get the JoyCon to report full data, but interpreting it would require lots of refactoring as the format of the report is different to the values coded to the enums. I'll try doing this over the week if I have time

**Comment by sam0x17** [comment]
nice -- would be great if we could use the full data!!

**Comment by HarryPeach** [comment]
I won't have very much time to work on this anymore as exams and coursework are piling up over the next few months so I'll write up a bit about what I've gotten working and what I learned here:

The code below will make the JoyCon switch to its full reporting mode:
`
const unsigned char buf[40] = { 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x03, 0x30 };
hid_write(left_joycon, buf, sizeof(buf));
`
- The first bit is 0x1 which is the prefix for all subcommands.
- The second bit is 0x0, and is the global packet number, this should increment by one for each packet that you send.
- The next 8 bits are rumble data.
- Bit number 11 is 0x03, which is the [subcommand to change the joycon's reporting mode](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md#subcommand-0x03-set-input-report-mode).
- The final bit is 0x30, which is the id for the standard full report mode. By default the joycon is in basic mode which is 0x3F.

Once you are in full report mode the JoyCon will start reporting at 60Hz rather than whenever an input is pressed. The data is sends will also be in [this format](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md#standard-input-report-format).

To get the full analog data you have to send a subcommand to [read from the SPI Flash](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md#subcommand-0x10-spi-flash-read) the [correct calibration data for the specific controller](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/spi_flash_notes.md#x6000-factory-configuration-and-calibration).

I managed to decode the JoyCon data for the left stick in my own fork and have [posted it in this gist](https://gist.github.com/HarryPeach/5953914cf4f3be17be3058bc0a81dc68).

I hope these notes help anyone else who wants to continue work on this issue as well as the following resources:

> SPI Flash interfacing: https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/spi_flash_notes.md
> Output Reports: https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md#standard-input-report-format
> Subcommands to the controller: https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md

**Comment by sam0x17** [comment]
@HarryPeach thanks a bunch for your work

**Comment by DavidSL448** [comment]
Hello!

I know that asking "how's progress" doesn't really accomplish much, especially since I'm no programmer and can't really help in any substantial way. Still, I was still wondering if you've kept working on this project? I've tried other Joycon "drivers", but yours seems to be the cleanest of the bunch - plus the others I've tried are extremely laggy. If you managed to add analog support, it would be so amazing!

Even if the answer is "no", I'd really appreciate knowing! Thanks for all the time you've poured into this until now!

**Comment by sam0x17** [comment]
@DavidSL448 For the moment I don't have any time to work on this. If analog support was a quick little patch I'd just do it, but the problem is it turns out you have to communicate with the joycons in an entirely different mode, which basically means I'd have to change the commands I use for doing everything, not just analog. I'm really, really hoping that another programmer can step in and help a little bit but eventually I will add this when I find the time. So I guess my answer is no, but only for now

**Comment by DavidSL448** [comment]
So it's more complicated than changing a few lines of code, huh? Oh well! Thanks for your quick reply. I'll keep an eye out for any future updates you might make in the coming months or years. Cheers!

**Comment by wormyrocks** [comment]
@sam0x17 I implemented this for the Unity Joy-Con library and am working on a pull request.

**Comment by sam0x17** [comment]
Fantastic -- thanks!

**Comment by wormyrocks** [comment]
Here 'tis --
https://github.com/wormyrocks/XJoy/commit/6e50108983e7e5d593ef2864ad42a96cc134d53f

**Comment by Liberte78** [comment]
WORKS LIKE A CHARM!!!
Thank YOU!!

**Comment by sam0x17** [comment]
if someone wants to cut a new release with this I'll approve it

**Comment by sam0x17** [comment]
now included in https://github.com/sam0x17/XJoy/releases/tag/v0.1.9

Thanks again @wormyrocks!
