### ISSUE TITLE
Multiple controllers

### ISSUE THREAD

**Issue by cimocw** [sam0x17/XJoy#11]
is there a way to have more than one pair of joycons working at the same time? I tried but all I got was the first pair registering the inputs on both instances of the application.

**Comment by sam0x17** [comment]
With the code the way it is, there is no way to do this, but you might be able to extend my code to handle this. https://github.com/sam0x17/XJoy/blob/master/XJoy/XJoy.cpp#L164 returns a list of all devices that are found that match the manufacturer and product specified. My code just takes the first one, but you could modify things so that it instantiates the first and second one. This is beyond the scope of what I plan to do though.

**Comment by cimocw** [comment]
I understand and appreciate your help. I don't code but will keep an eye on the project in case someone else does it. For the time being I think I can manage borrowing an extra pro controller to play multiplayer games. Keep up the good work!
