### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by WhatIsRove** [sam0x17/XJoy#28]
I see that others have been having the same issue a few months back,
I have reinstalled multiple versions of Visual C++ and multiple versions of XJoy but I can't get it to work.
First it gives the error Msvcp140.dll is missing so I found it online seperately and put it in the same folder, but then it brings out the 0xc000007b error and doesn't work, I have installed the ViGE bus drivers and what not and really want to get this working.

**Comment by sam0x17** [comment]
Sorry for the delay @WhatIsRove if you could go through some of the previous versions and see if any of those give you the issue as well that would help me a lot. If it doesn't work with any of them it has to be something weird with your system because it does work for a good number of people. Specifically what will help me is if you can figure out the version where it suddenly stops working. Then I can look at the changes introduced in that version and try to figure out what is causing your problem. Right now I have nothing to go on since it works on my two systems :/

**Comment by domenicoblanco** [comment]
Hi, I've the same issue and with version 0.1.4 it works for me

**Comment by domenicoblanco** [comment]
I fixed installing Visual Studio

**Comment by sam0x17** [comment]
It should now work with the latest release (which I re-released) as I have included the missing dll files.
