### ISSUE TITLE
Issue where you need debug Visual Studio DLL files for the application to work.

### ISSUE THREAD

**Issue by 0211beno** [sam0x17/XJoy#6]

**Comment by sam0x17** [comment]
@0211beno I've chased this issue a whole bunch already. What I do know is there is something about the release config that is requiring Visual Studio stuff, and I have no idea what it is. If you use the releases from the release page, the needed DLLs are packaged with the distribution, but definitely let me know if there is another DLL that it is complaining about. Otherwise, if anyone has any insight into what might be causing this, I'd love to fix this issue. I literally went through every line of the XJoy.vcproject file and I couldn't find anything that I thought might be causing this.

**Comment by sam0x17** [comment]
@0211beno I've added instructions to also install the Visual C++ 2017 Redistributable for Visual Studio to the README. This may or may not fix your issue. Let me know if it does. I'm assuming you were already using the latest release from the releases page?

**Comment by sam0x17** [comment]
@0211beno can you tell me what dll it is looking for?

**Comment by 0211beno** [comment]
VCRUNTIME140D.dll

**Comment by sam0x17** [comment]
@0211beno I have included the file you are missing in the latest release to see experimentally if it fixes your issue. You are using Windows 10 right?

In the mean time I am pursuing a more permanent fix on stackoverflow

**Comment by 0211beno** [comment]
I am using Windows 10. With the new version with included dll I get "Unable to start program error 0xc000007b

**Comment by sam0x17** [comment]
@0211beno I have swapped out some of the dlls in the 1.0.4 release  in such a way that this might get it to run on your machine -- still pursing a more permanent fix on stackoverflow.

Try this release: https://github.com/sam0x17/XJoy/releases/download/v1.1.4/XJoy.v0.1.4.zip

**Comment by 0211beno** [comment]
Now it works for me.

**Comment by sam0x17** [comment]
ok cool 👍
